OBJECTS = main.o bank.o

FLAGS  = -g -Wall -Werror -Wextra
VFLAGS = --leak-check=full --show-leak-kinds=all --track-origins=yes

all: $(OBJECTS)
	@gcc $(OBJECTS) -o exec $(FLAGS)

main.o: main.c bank.h
	@gcc main.c -c $(FLAGS)

bank.o: bank.c bank.h
	@gcc bank.c -c $(FLAGS)

run: all
	@./exec

valgrind: all
	@valgrind $(VFLAGS) ./exec

clean:
	@rm -rf *.o exec

zip:
	@zip bank.zip Makefile main.c bank.c bank.h
